# Generated by Django 4.2.2 on 2023-06-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasmd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doctor', models.IntegerField(null=True)),
                ('Doc_nomb', models.CharField(max_length=20, null=True)),
                ('Doc_Apellido', models.CharField(max_length=20, null=True)),
                ('especialidad', models.CharField(max_length=20, null=True)),
                ('Doc_direccion', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
