# Generated by Django 4.2.2 on 2023-07-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasmd', '0004_remove_citasmd_id_citasmd_citasmd_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_especialidad', models.CharField(max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='especialidad',
        ),
    ]
