# Generated by Django 4.2.2 on 2023-07-07 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citasmd', '0005_especialidad_remove_doctor_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citasmd.especialidad'),
        ),
    ]
